In [1]:
%run 02-connect.ipynb

In [2]:
%%sql

SELECT *
FROM billboard_top_100_year_end
LIMIT 10;

,year,year_rank,group,artist,song_name,id
0,1956.0,1.0,"""Elvis Presley""","""Elvis Presley""","""Heartbreak Hotel""",1
1,1956.0,2.0,"""Elvis Presley""","""Elvis Presley""","""Don't Be Cruel""",2
2,1956.0,3.0,"""Nelson Riddle""","""Nelson Riddle""","""Lisbon Antigua""",3
3,1956.0,4.0,"""Platters""","""Platters""","""My Prayer""",4
4,1956.0,5.0,"""Gogi Grant""","""Gogi Grant""","""The Wayward Wind""",5
5,1956.0,6.0,"""Les Baxter""","""Les Baxter""","""The Poor People Of Paris""",6
6,1956.0,7.0,"""Doris Day""","""Doris Day""","""Whatever Will Be Will Be (Que Sera Sera)""",7
7,1956.0,8.0,"""Elvis Presley""","""Elvis Presley""","""Hound Dog""",8
8,1956.0,9.0,"""Dean Martin""","""Dean Martin""","""Memories Are Made Of This""",9
9,1956.0,10.0,"""Kay Starr""","""Kay Starr""","""Rock And Roll Waltz""",10

In [3]:
%%sql

SELECT *
FROM billboard_top_100_year_end
WHERE year_rank BETWEEN 5 AND 10
LIMIT 10;

,year,year_rank,group,artist,song_name,id
0,1956.0,5.0,"""Gogi Grant""","""Gogi Grant""","""The Wayward Wind""",5
1,1956.0,6.0,"""Les Baxter""","""Les Baxter""","""The Poor People Of Paris""",6
2,1956.0,7.0,"""Doris Day""","""Doris Day""","""Whatever Will Be Will Be (Que Sera Sera)""",7
3,1956.0,8.0,"""Elvis Presley""","""Elvis Presley""","""Hound Dog""",8
4,1956.0,9.0,"""Dean Martin""","""Dean Martin""","""Memories Are Made Of This""",9
5,1956.0,10.0,"""Kay Starr""","""Kay Starr""","""Rock And Roll Waltz""",10
6,1957.0,5.0,"""Jimmy Dorsey""","""Jimmy Dorsey""","""So Rare""",108
7,1957.0,6.0,"""Pat Boone""","""Pat Boone""","""Don't Forbid Me""",109
8,1957.0,7.0,"""Guy Mitchell""","""Guy Mitchell""","""Singing The Blues""",110
9,1957.0,8.0,"""Sonny James""","""Sonny James""","""Young Love""",111

In [4]:
%%sql

SELECT *
FROM billboard_top_100_year_end
WHERE year_rank >= 5 AND year_rank <= 10
LIMIT 10;

,year,year_rank,group,artist,song_name,id
0,1956.0,5.0,"""Gogi Grant""","""Gogi Grant""","""The Wayward Wind""",5
1,1956.0,6.0,"""Les Baxter""","""Les Baxter""","""The Poor People Of Paris""",6
2,1956.0,7.0,"""Doris Day""","""Doris Day""","""Whatever Will Be Will Be (Que Sera Sera)""",7
3,1956.0,8.0,"""Elvis Presley""","""Elvis Presley""","""Hound Dog""",8
4,1956.0,9.0,"""Dean Martin""","""Dean Martin""","""Memories Are Made Of This""",9
5,1956.0,10.0,"""Kay Starr""","""Kay Starr""","""Rock And Roll Waltz""",10
6,1957.0,5.0,"""Jimmy Dorsey""","""Jimmy Dorsey""","""So Rare""",108
7,1957.0,6.0,"""Pat Boone""","""Pat Boone""","""Don't Forbid Me""",109
8,1957.0,7.0,"""Guy Mitchell""","""Guy Mitchell""","""Singing The Blues""",110
9,1957.0,8.0,"""Sonny James""","""Sonny James""","""Young Love""",111